import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const redirectToClient = async (e) => {
    e.preventDefault();
    router.push(`/client/${e.target.tableNo.value}`);
  };

  return (
    <>
      <Head>
        <title>Order Taking System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        Please enter your table number:
        <form
          className={styles.orderForm}
          name="tableNoForm"
          autoComplete="off"
          onSubmit={redirectToClient}
        >
          <input
            type="number"
            required
            id="tableNo"
            name="tableNo"
            className={styles.inputStyle}
          />
          <input
            type="submit"
            value="Proceed"
            id="btnsubmit"
            className={styles.submitButton}
          />
        </form>
      </main>
    </>
  );
}
